name: metrics

on:
  schedule: [{ cron: "0 * * * *" }]
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: 📘 Markdown template
        uses: lowlighter/metrics@0f720e83521d609f4d0f69c5f370e60c9f9e93ef
        if: ${{ success() || failure() }}
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          template: markdown
          filename: README.md
          markdown: https://raw.githubusercontent.com/xHyroM/xHyroM/main/.github/metrics.template.md
          config_output: markdown
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Bratislava

          # Achievements
          plugin_achievements: yes
          plugin_achievements_display: compact

          # Followup
          plugin_followup: yes
          plugin_followup_sections: user

          # Isocalendar
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

          # Language
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
          plugin_languages_skipped: discord-datamining

          output_action: commit
